### ISSUE TITLE
Could anyone can share the train time?

### ISSUE THREAD

**Issue by AndrewZhao** [amdegroot/ssd.pytorch#101]
The training time in my code is so long. It will take 8 seconds about the forward and backward process.
Could anyone can share the train time for an iteration? when the batch is 32 or 16 and use cuda.
thanks very much

**Comment by amdegroot** [comment]
Hmm, that seems unusual.  Can you paste the output you see when training? When I run on my GTX 1080, I see forward and backward times around 0.2 sec on a batch of 32. The first iteration time will be longer (maybe around 7 or 8 sec since everything is being loaded into memory). 
Here is the output in terminal for my first 40 iterations (Timer refers to single iteration time):
`Timer: 7.2530 sec.
iter 0 || Loss: 27.0166 || Saving state, iter: 0
Timer: 0.2107 sec.
iter 10 || Loss: 15.7912 || Timer: 0.2110 sec.
iter 20 || Loss: 17.3288 || Timer: 0.2107 sec.
iter 30 || Loss: 16.7687 || Timer: 0.2109 sec.
iter 40 || Loss: 12.1029 || Timer: 0.2092 sec.`

**Comment by bspivey** [comment]
Nice example. I am seeing timer: 0.4015 sec. on my EVGA GTX 1080 after 10 iterations.
iter 50230 || Loss: 4.7412 || timer: 0.4015 sec.
