### ISSUE TITLE
Variance not used in priorbox?

### ISSUE THREAD

**Issue by yxchng** [amdegroot/ssd.pytorch#39]
I notice that you did not use the variance in priorbox. Is it supposed to be like this? The caffe code has the following which you seem to have left out

```
top_data += top[0]->offset(0, 1);
  if (variance_.size() == 1) {
    caffe_set<Dtype>(dim, Dtype(variance_[0]), top_data);
  } else {
    int count = 0;
    for (int h = 0; h < layer_height; ++h) {
      for (int w = 0; w < layer_width; ++w) {
        for (int i = 0; i < num_priors_; ++i) {
          for (int j = 0; j < 4; ++j) {
            top_data[count] = variance_[j];
            ++count;
          }
        }
      }
    }
  }
}
```

Though I do not understand what the offset and caffe_set does. Do you have any idea?

**Comment by amdegroot** [comment]
I do include variance, but I store it more efficiently.  Since the variance consists of just 0.0 and 0.1, I store it as a constant list and use it in encoding and decoding as shown [here](https://github.com/amdegroot/ssd.pytorch/blob/master/layers/box_utils.py#L132).  `caffe_set` and -`>offset()` are ways of shifting and setting the underlying storage.  Thankfully, PyTorch extracts most of that for us. The reason he probably carries around the variance to begin with rather than just storing it separately is because his code is more experimental as it was used in creating the original SSD.
