### ISSUE TITLE
A bug in box_utils.py, log_sum_exp

### ISSUE THREAD

**Issue by jxlijunhao** [amdegroot/ssd.pytorch#85]
I change the batch_size to  2  , it there any solutions ?

File "train.py", line 232, in <module>
    train()
  File "train.py", line 184, in train
    loss_l, loss_c = criterion(out, targets)
  File "/home/junhao.li/anaconda2/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/lijunhao_dataset/pytorch_proj/SSD/ssd.pytorch/layers/modules/multibox_loss.py", line 95, in forward
    loss_c = log_sum_exp(batch_conf) - batch_conf.gather(1, conf_t.view(-1, 1))
  File "/data/lijunhao_dataset/pytorch_proj/SSD/ssd.pytorch/layers/box_utils.py", line 168, in log_sum_exp
    return torch.log(torch.sum(torch.exp(x-x_max), 1, keepdim=True)) + x_max
**RuntimeError: value cannot be converted to type float without overflow: inf**

**Comment by zhangyu233** [comment]
I  met the same problem, have you solved it?

**Comment by qijiezhao** [comment]
I met the same error, have you solved it?

**Comment by moyans** [comment]
@amdegroot

**Comment by walnutmandu** [comment]
I met the same error, have you solved it? @amdegroot

**Comment by amdegroot** [comment]
You may have to lower the learning rate when you go to a smaller batch size for training to be stable -- see similar [issue](https://github.com/weiliu89/caffe/issues/93).  

Also, not sure if this [bug](https://discuss.pytorch.org/t/value-cannot-be-converted-to-type-double-without-overflow-inf/11752/5) is fixed yet, but PyTorch Variables do not currently handle inf values, hence the error message you saw.

**Comment by MasakazuYposhimura** [comment]
I also encountered the same problem. 
Furthermore, in my case, losses didn't be inf because of the choices in hard negative mining and it took much time to find where is wrong...

`x_max = x.data.max()
return torch.log(torch.sum(torch.exp(x-x_max), 1, keepdim=True)) + x_max`
This code solve the inf problem of exp but there are still the risks of inf problem of log. 

So, I changed the code as follows and the program could predict properly.
`#x_max = x.data.max()
x_max, x_max_indices = torch.max(x, dim=1, keepdim=True)
return torch.log(torch.sum(torch.exp(x-x_max), 1, keepdim=True)) + x_max`
